export const SET_LOADING= "SET_LOADING";

export const SET_SERVICE_LIST = "SET_SERVICE_LIST";
export const SET_SERVICE_DETAIL = "SET_SERVICE_DETAIL";
export const SET_SERVICE_ERROR = "SET_SERVICE_ERROR";

export const REPEAT_REQUEST = "REPEAT_REQUEST";

